const SUPABASE_URL='https://vprfybqpgeburxdjqcdi.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_Ir2iZjHu6onRXjTHEFq0zg_Ga1v-HAC';
const API=SUPABASE_URL+'/rest/v1';
const H={'apikey':SUPABASE_PUBLISHABLE_KEY,'Authorization':'Bearer '+SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json'};
const qs=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const petIcon=p=>p.species==='Gato'?'🐱':p.species==='Cachorro'?'🐶':'🐾';
function code(){const a=new Uint32Array(1);crypto.getRandomValues(a);return 'PET-'+a[0].toString(36).slice(0,6).toUpperCase().padEnd(6,'X')}
function hideAll(){['home','register','dashboard','writer','finder','publicProfile'].forEach(id=>qs(id)?.classList.add('hidden'))}
function goHome(){hideAll();qs('home').classList.remove('hidden');history.replaceState({},'',location.pathname)}
function showSection(id){hideAll();qs(id).classList.remove('hidden');if(id==='dashboard')renderDashboard()}
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{...H,...(opt.headers||{})}});if(!r.ok)throw new Error(await r.text());const t=await r.text();return t?JSON.parse(t):null}
async function createPet(p){const x=await api('/pets',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(p)});return x?.[0]}
async function getPets(){return api('/pets?select=*&order=created_at.desc')}
async function getPet(c){const x=await api('/pets?select=*&public_code=eq.'+encodeURIComponent(c)+'&limit=1');return x?.[0]||null}
async function setLost(c,lost){return api('/pets?public_code=eq.'+encodeURIComponent(c),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({lost})})}
qs('petForm').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;if(b){b.disabled=true;b.textContent='Salvando...'};const p={public_code:code(),name:qs('name').value.trim(),species:qs('species').value,breed:qs('breed').value.trim(),sex:qs('sex').value,color:qs('color').value.trim(),owner_name:qs('owner').value.trim(),phone:qs('phone').value.trim(),whatsapp:qs('whatsapp').value.trim(),city:qs('city').value.trim(),district:qs('district').value.trim(),address:qs('address').value.trim(),notes:qs('notes').value.trim(),lost:false};try{const s=await createPet(p);e.target.reset();await openWriter(s.public_code)}catch(err){alert('Erro ao salvar no Supabase: '+err.message)}finally{if(b){b.disabled=false;b.textContent='Criar perfil'}}});
async function renderDashboard(){const box=qs('petsGrid');box.innerHTML='<div class="notice">Carregando...</div>';try{const pets=await getPets();box.innerHTML=pets.length?pets.map(p=>`<article class="pet-card"><div class="pet-icon">${petIcon(p)}</div><h3>${esc(p.name)}</h3><div class="muted">${esc(p.species)}${p.breed?' • '+esc(p.breed):''}</div><div class="code">${esc(p.public_code)}</div><span class="status ${p.lost?'lost':''}">${p.lost?'PET PERDIDO':'ATIVO'}</span><div class="card-actions"><button class="secondary" onclick="openProfile('${p.public_code}')">Ver perfil</button><button class="primary" onclick="openWriter('${p.public_code}')">Gravar NFC</button><button class="ghost" onclick="toggleLost('${p.public_code}',${!p.lost})">${p.lost?'Marcar encontrado':'Marcar perdido'}</button></div></article>`).join(''):'<div class="notice">Nenhum pet cadastrado.</div>'}catch(e){box.innerHTML='<div class="notice warning">Erro: '+esc(e.message)+'</div>'}}
async function toggleLost(c,v){try{await setLost(c,v);renderDashboard()}catch(e){alert('Erro ao atualizar: '+e.message)}}
function profileUrl(c){const u=new URL(location.href);u.search='?pet='+encodeURIComponent(c);u.hash='';return u.toString()}
async function openWriter(c){const p=await getPet(c);if(!p)return;hideAll();qs('writer').classList.remove('hidden');const url=profileUrl(c);qs('writerContent').innerHTML=`<div class="nfc-box"><div class="nfc-icon">📡</div><h3>Vincular NTAG213 ao ${esc(p.name)}</h3><div class="urlbox">${esc(url)}</div><button class="primary big" onclick="writeNfc('${c}')">Encostar e gravar a tag</button><button class="secondary big" style="margin-left:8px" onclick="copyTagUrl('${c}')">Copiar link</button><div id="writeStatus"></div></div><div class="notice warning"><b>iPhone:</b> se o Safari não oferecer gravação NFC, use um app NFC compatível para gravar o link acima.</div>`}
async function copyTagUrl(c){const u=profileUrl(c);try{await navigator.clipboard.writeText(u);qs('writeStatus').innerHTML='<div class="notice success">✅ Link copiado.</div>'}catch{prompt('Copie este link:',u)}}
async function writeNfc(c){const s=qs('writeStatus'),u=profileUrl(c);if(!('NDEFReader'in window)){s.innerHTML='<div class="notice warning">Este navegador não grava NFC. Use “Copiar link” e grave a URL em um app NFC compatível.</div>';return}try{s.innerHTML='<div class="notice">Aproxime a NTAG213...</div>';const n=new NDEFReader();await n.write({records:[{recordType:'url',data:u}]});s.innerHTML='<div class="notice success">✅ Tag gravada.</div>'}catch(e){s.innerHTML='<div class="notice warning">Erro: '+esc(e.message)+'</div>'}}
function profileHtml(p){const n=(p.whatsapp||p.phone||'').replace(/\D/g,''),wa='https://wa.me/55'+n+'?text='+encodeURIComponent('Olá! Encontrei o '+p.name+' pela PetTag '+p.public_code+'.');return `<div class="profile-photo">${petIcon(p)}</div><span class="status ${p.lost?'lost':''}">${p.lost?'🚨 PET PERDIDO':'🐾 PET CADASTRADO'}</span><h1>${esc(p.name)}</h1><p class="muted">${esc(p.species)}${p.breed?' • '+esc(p.breed):''}</p>${p.color?'<p><b>Características:</b> '+esc(p.color)+'</p>':''}${p.city?'<p><b>Cidade:</b> '+esc(p.city)+(p.district?' • '+esc(p.district):'')+'</p>':''}${p.notes?'<p><b>Observações:</b> '+esc(p.notes)+'</p>':''}<div class="notice">${p.lost?'O tutor informou que este animal está perdido.':'Este animal possui um tutor cadastrado.'}</div><div class="profile-actions"><a class="call" href="tel:${esc(p.phone)}">📞 Ligar para o tutor</a><a class="wa" href="${wa}" target="_blank" rel="noopener">💬 Chamar no WhatsApp</a></div>`}
async function openProfile(c){hideAll();qs('publicProfile').classList.remove('hidden');qs('publicProfile').innerHTML='<div class="notice">Carregando...</div>';try{const p=await getPet(c);qs('publicProfile').innerHTML=p?profileHtml(p):'<div class="notice warning">Pet não encontrado.</div>';if(p)history.replaceState({},'',location.pathname+'?pet='+encodeURIComponent(c))}catch(e){qs('publicProfile').innerHTML='<div class="notice warning">Erro: '+esc(e.message)+'</div>'}}
async function findPet(){const c=qs('finderCode').value.trim().toUpperCase(),box=qs('finderResult');box.innerHTML='<div class="notice">Buscando...</div>';try{const p=await getPet(c);box.innerHTML=p?'<div class="public-profile" style="margin-top:20px">'+profileHtml(p)+'</div>':'<div class="notice warning">Tag não encontrada.</div>'}catch(e){box.innerHTML='<div class="notice warning">Erro: '+esc(e.message)+'</div>'}}
(async()=>{const id=new URLSearchParams(location.search).get('pet');if(id)await openProfile(id);else goHome()})();